### ISSUE TITLE
doc: fix broken link in README.md

### ISSUE THREAD

**Issue by tungbq** [tungbq/devops-project#46]
Broken link found in project07 column: https://github.com/tungbq/devops-project/blob/main/README.md
Correct link should be: https://github.com/tungbq/devops-project/tree/main/projects/terraform-free-vpn-on-aws

**Comment by deardeleta** [comment]
Hey There,

I've completed this task.

**Comment by tungbq** [comment]
Thank you very much! I will review and merge your PR
